site_name: Tech Notes

nav:
    - Home: index.md
    - 'Powershell':
      - 'Powershell Note': Powershell/README.md
      - 'PS Modules Note': Powershell/Module.md
      - 'PS Functions Note': Powershell/Functions.md
    - DockerSwarm: DockerSwarm/README.md
    - Kubernetes: Kubernetes/KubernetesNotes.md
    - Sites: Sites/README.md
    - AWS: 
      - "CloudFormation": AWS/CloudFormation.md
      - "Snapshot manager": AWS/SnapshotManager.md
theme: readthedocs
